import type { Metadata } from "next";

import "./globals.css";
import { ThemeProvider } from "../components/theme-provider";

export const metadata: Metadata = {
  title: "GTA",
  description: "Generated by create next app",
  icons: {
    icon: "/assets/favicon.ico", // Corrected typo in "assets"
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={` bg-white dark:bg-[#0a0a0a]`}>
        {/* ThemeProvider ensures consistent theme rendering */}
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
