import type { Metadata } from "next";
import { ToastContainer, Bounce } from "react-toastify"

import "./globals.css";
import { ThemeProvider } from "../components/theme-provider";
import localfont from "next/font/local";

const lato = localfont({
  src: [
    {
      path: "../../public/fonts/Lato-Regular.ttf",
    },
  ],
  variable: "--font-lato",
});

export const metadata: Metadata = {
  title: "GTA",
  description: "Generated by create next app",
  icons: {
    icon: "/assets/favicon.ico", // Corrected typo in "assets"
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${lato.variable} bg-white dark:bg-[#0a0a0a]`}>
        {/* ThemeProvider ensures consistent theme rendering */}
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <ToastContainer
            position="top-center"
            autoClose={5000}
            hideProgressBar={false}
            newestOnTop={false}
            closeOnClick={false}
            rtl={false}
            pauseOnFocusLoss
            draggable
            pauseOnHover
            theme="colored"
            transition={Bounce}
          />
          <div className="  ">
            <div className=" ">{children}</div>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
