import type { Metadata } from "next";

import "./globals.css";
import { ThemeProvider } from "../components/theme-provider";
import localfont from "next/font/local";

const lato = localfont({
  src: [
    {
      path: "../../public/fonts/Lato-Regular.ttf",
    },
  ],
  variable: "--font-lato",
});

export const metadata: Metadata = {
  title: "GTA",
  description: "Generated by create next app",
  icons: {
    icon: "/assets/favicon.ico", // Corrected typo in "assets"
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${lato.variable} bg-white dark:bg-[#0a0a0a]`}>
        {/* ThemeProvider ensures consistent theme rendering */}
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="  ">
            <div className=" ">{children}</div>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
